---
title: "Qasim's Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(shiny)
library(dplyr)
```
# Page 1
Column
-----------------------------------------------------------------------


### Importing Data from csv
```{r, include=FALSE}
df_raw <- read_csv("data_cleaned.csv")


```


## Summarize the Data
```{r}

df_raw %>% group_by(Gender) %>%  count()

```

Column 
-----------------------------------------------------------------------

### Chart C

```{r}
#df_raw %>% colnames()

```


```{r}



```

### Chart C

```{r}


total_count <- df_raw %>% count()
categorical <- c('Gender','Enrolled')

numeric <- c('Age')


```


Column{.sidebar} 
-----------------------------------------------------------------------


```{r}

selectInput(inputId = "categorical_variable",label="Select Categorical Variable", choices = categorical)
selectInput(inputId = "numeric_variable",label="Select Numeric Variable", choices = numeric)
sliderInput(inputId = "Age", label="Select Age Range", min=17,max=60,value=24)




```

```{r}







```




# Page 2