---
title: "Qasim DS Project 1"
author: "Qasim Basra"
date: "2022-09-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(dplyr)
library(ggplot2)

```

## Importing Python Packages 
```{python}
import pandas as pd
import numpy as np


```


## Importing the Data

```{r , warning=FALSE,message=FALSE}

course_data <- read_csv("Data/Data - DS C1 Course.csv")


```

## Data Summary
```{r}
#summary(course_data)

```

## Inspecting Columns names of the Data

```{r, echo=FALSE}

colnames(course_data)


```





## Inspecting null values in the dataset

```{r}

#is.na(course_data)

```

## Geometric Point Visulization of City student residing versus age

```{r}

ggplot(data= course_data,aes(x= Age, y=`Which City are you currently residing in?`))+
  geom_point()


```







## Running python in R Studio


```{r EDA }


library(reticulate)



```

## Running Python in R
We will demonstrate how python will run in RStudio.



## Inspecting unique entities across all the columns
```{python}

df=pd.read_csv("Data/Data - DS C1 Course.csv")
for x in df:
  print(df[x].unique())
```




