---
title: "CubeStatistica Students FlexDashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```
```{r}
library("tidyverse")
library("dplyr")
library("knitr")
library("kableExtra")
```



# Dashboard 01

Column {data-width=400}
-----------------------------------------------------------------------



### Char 01

```{r}
dfRaw <- read_csv(("Data/Data - DS C1 Course.csv"))
#head(dfRaw)
# df_paid %>% group_by(`Do you understand that this is a paid course ?...3`) %>% summarize(n=n())
df_paid <- dfRaw %>% group_by(`Do you understand that this is a paid course ?...3`) %>% count()  
ggplot (df_paid, aes (x = `Do you understand that this is a paid course ?...3`, y = n)) + geom_bar(stat ="identity", fill = "green")


df_age <- dfRaw %>% group_by(`Age`) %>% count()  
ggplot (df_age, aes (x = Age , y = n)) + geom_bar(stat ="identity", fill = "green")
```



Column {data-width=400}
-----------------------------------------------------------------------

### Chart B

```{r}
dfRaw %>% group_by(Gender)  %>% count() %>% kable()



```

### Chart C

```{r}

```

